### Приветствие
GET localhost:8080/calculator/

### Сложение
GET localhost:8080/calculator/plus?num1=5

### Вычитание
GET localhost:8080/calculator/minus?num1=5&num2=5

### Умножение
GET localhost:8080/calculator/multiply?num1=5&num2=5

### Деление
GET localhost:8080/calculator/divide?num1=5&num2=0